name: Angelica

on:
  workflow_dispatch:
  push:

permissions:
  contents: write

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-22.04
    steps:
      - name: Build
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/MiCode/Xiaomi_Kernel_OpenSource
          kernel-branch: dandelion-q-oss
          config: angelica_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          android-version: 10
          aosp-clang-version: r353983c
          anykernel3: true
          release: true
          access-token: ${{ secrets.GITHUB_TOKEN }}