name: Angelica

on:
  workflow_dispatch:
  push:

permissions:
  contents: write

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout kernel source
        uses: actions/checkout@v4
        with:
          repository: MiCode/Xiaomi_Kernel_OpenSource
          ref: dandelion-q-oss
          path: kernel/source

      - name: Checkout Custom Repo
        uses: actions/checkout@v4
        with:
          path: custom_files

      - name: Some fix
        run: |
          cp "$GITHUB_WORKSPACE/custom_files/angelica/DrvGen.py" ./kernel/source/tools/dct

      - name: Build
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: ./kernel/source/
          kernel-branch: dandelion-q-oss
          config: angelica_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          android-version: 10
          aosp-clang-version: r353983c
          anykernel3: true
          release: true
          access-token: ${{ secrets.GITHUB_TOKEN }}