name: Build Kernel

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Custom Repo
        uses: actions/checkout@v4
        with:
          path: custom_files

      - name: Setup Repo Tool
        run: |
          sudo apt-get update
          sudo apt-get install -y patch
          sudo curl -o /usr/local/bin/repo https://storage.googleapis.com/git-repo-downloads/repo
          sudo chmod a+x /usr/local/bin/repo
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Repo Init and Sync
        run: |
          mkdir -p android-kernel && cd android-kernel
          repo init -u https://android.googlesource.com/kernel/manifest -b common-android12-5.10 --depth=1
          repo sync -c -j$(nproc --all) --no-tags --no-clone-bundle --force-sync

      - name: Apply All Patch Files
        run: |
          cd android-kernel/common
          if [ -d "$GITHUB_WORKSPACE/custom_files/patches" ]; then
            for p in "$GITHUB_WORKSPACE/custom_files/patches"/*.patch; do
              if [ -f "$p" ]; then
                patch -p1 < "$p"
              fi
            done
          fi

      - name: Merge All Custom Fragments
        run: |
          cd android-kernel
          if [ -d "$GITHUB_WORKSPACE/custom_files/fragments" ]; then
            FRAGMENTS=("$GITHUB_WORKSPACE/custom_files/fragments"/*.fragment)
            if [ -f "${FRAGMENTS[0]}" ]; then
              ARCH=arm64 common/scripts/kconfig/merge_config.sh -m common/arch/arm64/configs/gki_defconfig "${FRAGMENTS[@]}"
              mv .config common/arch/arm64/configs/gki_defconfig
            fi
          fi

      - name: Fix defconfig
        run: |
          cd android-kernel
          find common/ -type f -name "build.config*" -exec sed -i 's/check_defconfig//g' {} +

      - name: Commit Local Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          cd android-kernel/common
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "build: auto-commit local changes to avoid -dirty suffix"
          fi

      - name: Build Kernel
        run: |
          cd android-kernel
          export KCFLAGS="-O3 -pipe -fno-plt -fno-semantic-interposition -fomit-frame-pointer"
          export KCPPFLAGS="-O3 -pipe"
          export LDFLAGS_vmlinux="--no-keep-memory"
          
          BUILD_CONFIG=common/build.config.gki.aarch64 build/build.sh

      - name: Upload Kernel Artifact
        uses: actions/upload-artifact@v4
        with:
          name: kernel
          path: android-kernel/out/android12-5.10/dist/*
