name: Build Kernel

on:
  workflow_dispatch:

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Build
        uses: dabao1955/kernel_build_action@main
        with:
          kernel_url: https://github.com/MiCode/Xiaomi_Kernel_OpenSource
          kernel_branch: surya-q-oss
          defconfig: vendor/atoll_defconfig
          arch: arm64
          aosp_gcc: true
          aosp_clang: true
          android_version: 10
          clang_version: r416183b
          anykernel3: true
          release: true
          token: ${{ secrets.GITHUB_TOKEN }}
